### ISSUE TITLE
Error: Failure while executing; `/opt/homebrew/bin/brew tap homebrew/services` exited with 1.

### ISSUE THREAD

**Issue by akoserwal** [chipmk/docker-mac-net-connect#18]
➜  ~ sudo brew services start chipmk/tap/docker-mac-net-connect
Password:
Error: Running Homebrew as root is extremely dangerous and no longer supported.
As Homebrew does not drop privileges on installation you would be giving all
build scripts full access to your system.
Error: Failure while executing; `/opt/homebrew/bin/brew tap homebrew/services` exited with 1.

**Comment by gregnr** [comment]
Hey @akoserwal thanks for the report. Can you confirm:
- Homebrew version
- OS version
- Intel/Apple Silicon?

`docker-mac-net-connect` requires root privileges to run (see https://github.com/chipmk/docker-mac-net-connect#why-does-the-service-need-to-run-as-root). If `brew services` no longer allows this, we will need to come up with a new way to run in.

I did just try this on macOS 13.2.1 + Homebrew 4.0.13 on an M2 and didn't receive the above message.

**Comment by gregnr** [comment]
Closing this for now as this doesn't seem to be an issue today on latest versions of `brew` and macOS - please reopen though if this error continues to occur!
