### ISSUE TITLE
met up with some network problems

### ISSUE THREAD

**Issue by mingmingshiliyu** [chipmk/docker-mac-net-connect#31]
``` shell
wtst45x@MacBook-Pro mongo % go env|grep -i proxy                          
GONOPROXY=''
GOPROXY='https://goproxy.cn,direct'


wtst45x@MacBook-Pro mongo % brew install chipmk/tap/docker-mac-net-connect
==> Fetching chipmk/tap/docker-mac-net-connect
==> Downloading https://github.com/chipmk/docker-mac-net-connect/archive/refs/tags/v0.1.2.tar.gz

Already downloaded: /Users/wtst45x/Library/Caches/Homebrew/downloads/be6ddea4c4a482e7843b5d9af1de1ea1fc218b83ea19a6b12b15081e2ce8983f--docker-mac-net-connect-0.1.2.tar.gz
==> Installing docker-mac-net-connect from chipmk/tap
==> make VERSION=v0.1.2 build-go
Last 15 lines from /Users/wtst45x/Library/Logs/Homebrew/docker-mac-net-connect/01.make:
go: downloading golang.zx2c4.com/wireguard v0.0.0-20211106133050-23d4e52ac97f
go: downloading github.com/docker/docker v20.10.10+incompatible
go: downloading golang.zx2c4.com/wireguard/wgctrl v0.0.0-20211027115401-c9b1ec1aa6d8
networkmanager/networkmanager.go:8:2: github.com/docker/docker@v20.10.10+incompatible: Get "https://proxy.golang.org/github.com/docker/docker/@v/v20.10.10+incompatible.zip": dial tcp 172.253.122.141:443: i/o timeout
main.go:17:2: github.com/docker/docker@v20.10.10+incompatible: Get "https://proxy.golang.org/github.com/docker/docker/@v/v20.10.10+incompatible.zip": dial tcp 172.253.122.141:443: i/o timeout
main.go:18:2: github.com/docker/docker@v20.10.10+incompatible: Get "https://proxy.golang.org/github.com/docker/docker/@v/v20.10.10+incompatible.zip": dial tcp 172.253.122.141:443: i/o timeout
main.go:19:2: github.com/docker/docker@v20.10.10+incompatible: Get "https://proxy.golang.org/github.com/docker/docker/@v/v20.10.10+incompatible.zip": dial tcp 172.253.122.141:443: i/o timeout
main.go:20:2: github.com/docker/docker@v20.10.10+incompatible: Get "https://proxy.golang.org/github.com/docker/docker/@v/v20.10.10+incompatible.zip": dial tcp 172.253.122.141:443: i/o timeout
main.go:21:2: golang.zx2c4.com/wireguard@v0.0.0-20211106133050-23d4e52ac97f: Get "https://proxy.golang.org/golang.zx2c4.com/wireguard/@v/v0.0.0-20211106133050-23d4e52ac97f.zip": dial tcp 172.253.122.141:443: i/o timeout
main.go:22:2: golang.zx2c4.com/wireguard@v0.0.0-20211106133050-23d4e52ac97f: Get "https://proxy.golang.org/golang.zx2c4.com/wireguard/@v/v0.0.0-20211106133050-23d4e52ac97f.zip": dial tcp 172.253.122.141:443: i/o timeout
main.go:23:2: golang.zx2c4.com/wireguard@v0.0.0-20211106133050-23d4e52ac97f: Get "https://proxy.golang.org/golang.zx2c4.com/wireguard/@v/v0.0.0-20211106133050-23d4e52ac97f.zip": dial tcp 172.253.122.141:443: i/o timeout
main.go:24:2: golang.zx2c4.com/wireguard@v0.0.0-20211106133050-23d4e52ac97f: Get "https://proxy.golang.org/golang.zx2c4.com/wireguard/@v/v0.0.0-20211106133050-23d4e52ac97f.zip": dial tcp 172.253.122.141:443: i/o timeout
main.go:25:2: golang.zx2c4.com/wireguard/wgctrl@v0.0.0-20211027115401-c9b1ec1aa6d8: Get "https://proxy.golang.org/golang.zx2c4.com/wireguard/wgctrl/@v/v0.0.0-20211027115401-c9b1ec1aa6d8.zip": dial tcp 172.253.122.141:443: i/o timeout
main.go:26:2: golang.zx2c4.com/wireguard/wgctrl@v0.0.0-20211027115401-c9b1ec1aa6d8: Get "https://proxy.golang.org/golang.zx2c4.com/wireguard/wgctrl/@v/v0.0.0-20211027115401-c9b1ec1aa6d8.zip": dial tcp 172.253.122.141:443: i/o timeout
make: *** [build-go] Error 1
```

**Comment by gregnr** [comment]
Hey @mingmingshiliyu, thanks for reporting this. After a deep dive, I discovered that Homebrew filters out local environment variables and Go configuration set in `go env`.

I've added special support for `GOPROXY` using a variable called `HOMEBREW_GOPROXY`. You can now install the formulae using a specific `GOPROXY` like this:

```bash
HOMEBREW_GOPROXY=https://my-proxy-url brew install chipmk/tap/docker-mac-net-connect
```

I've also added this to the docs [here](https://github.com/chipmk/docker-mac-net-connect/tree/main#goproxy-support). Could you try this and let me know if it solves your issue?

**Comment by mingmingshiliyu** [comment]
> Hey @mingmingshiliyu, thanks for reporting this. After a deep dive, I discovered that Homebrew filters out local environment variables and Go configuration set in `go env`.
> 
> I've added special support for `GOPROXY` using a variable called `HOMEBREW_GOPROXY`. You can now install the formulae using a specific `GOPROXY` like this:
> 
> ```shell
> HOMEBREW_GOPROXY=https://my-proxy-url brew install chipmk/tap/docker-mac-net-connect
> ```
> 
> I've also added this to the docs [here](https://github.com/chipmk/docker-mac-net-connect/tree/main#goproxy-support). Could you try this and let me know if it solves your issue?

![image](https://github.com/chipmk/docker-mac-net-connect/assets/143821597/658d4c67-1c65-42c2-94f7-b5e41c679974)

**Comment by gregnr** [comment]
It looks like it's using your custom `GOPROXY`. Does that proxy work for you when you normally use `go`? (you can try cloning this repo and running `make build-go`)

**Comment by mingmingshiliyu** [comment]
> Hey @mingmingshiliyu, thanks for reporting this. After a deep dive, I discovered that Homebrew filters out local environment variables and Go configuration set in `go env`.
> 
> I've added special support for `GOPROXY` using a variable called `HOMEBREW_GOPROXY`. You can now install the formulae using a specific `GOPROXY` like this:
> 
> ```shell
> HOMEBREW_GOPROXY=https://my-proxy-url brew install chipmk/tap/docker-mac-net-connect
> ```
> 
> I've also added this to the docs [here](https://github.com/chipmk/docker-mac-net-connect/tree/main#goproxy-support). Could you try this and let me know if it solves your issue?

it works!
