### ISSUE TITLE
[Question] failed to start service

### ISSUE THREAD

**Issue by vie-serendipity** [chipmk/docker-mac-net-connect#38]
When I run sudo sudo brew services start chipmk/tap/docker-mac-net-connect, I got
```
==> Successfully started `docker-mac-net-connect` (label: homebrew.mxcl.docker-mac-net-connect)
```
But I found the network is not connected.
WhenI run brew services list, it seems something unexpected happen. I didn't find any error logs in /opt/homebrew/var/log/docker-mac-net-connect.
My computer is mac m3 pro, I'm not sure this tool should work fine on m3.
```
➜  ~ brew services list                                        
Name                   Status     User File
docker-mac-net-connect error  256 root ~/Library/LaunchAgents/homebrew.mxcl.docker-mac-net-connect.plist
```

**Comment by gregnr** [comment]
Hey @vie-serendipity sorry for the delay. When you run `brew` under `sudo`, it runs under a different (root) user which is likely why you are seeing that `error` status. Can you please run the list command as `sudo` and let me know what it comes back with?

```shell
sudo brew services list
```

**Comment by vie-serendipity** [comment]
@gregnr When I add sudo, the status is `started` and everything is fine. Thanks.
