### ISSUE TITLE
Doesn't work on M3 Mac

### ISSUE THREAD

**Issue by danieljausovec** [chipmk/docker-mac-net-connect#45]
Hi,

Does anyone has a problem with multi networking on Mac with M3 chip? 
It doesn't resolve network correctly. It reached the docker container but it doesn't resolve any url path.

Can you please help me to resolve this issue.

After listing `brew services` I saw an error:

```
Name                   Status     User File
docker-mac-net-connect error  256 root ~/Library/LaunchAgents/homebrew.mxcl.docker-mac-net-connect.plist
```

It works on M2 chip with the same configuration.

**Comment by danieljausovec** [comment]
UPDATE:

After grep network details by IP I found out that on M2 chip the Gateway is set `utun0` and on M3 chip is `utun6`

```
$ sudo netstat -rnf inet | grep 10.100

Destination           Gateway         Flags               Netif
10.100.200/24      utun6              USc                 utun6
```

@gregnr can you please take a look?

**Comment by danieljausovec** [comment]
@gregnr I found a bug which was **not** on that package but in Django Framework which wrapped CORS error to 404 for no reason.

Sorry for open an issue for no reason. I'm closing it now because it works like expected!

**Comment by gregnr** [comment]
All good! Glad you solved it 👍
