### ISSUE TITLE
Starting of brew service homebrew.mxcl.docker-mac-net-connect.plist fails 

### ISSUE THREAD

**Issue by alexandertsukanov** [chipmk/docker-mac-net-connect#5]
Hi, @gregnr ! Thank you for wonderful brew package.
I have some issue: it looks like the brew service couldn't start. 
<img width="885" alt="image" src="https://user-images.githubusercontent.com/17796771/152531420-5436e040-04e4-4ae0-812d-b99fd3e247bc.png">
Here is my mac:
<img width="567" alt="image" src="https://user-images.githubusercontent.com/17796771/152531568-78432e90-de0c-4a37-bdc2-07c6530fe3dd.png">
Also, I have checked logs file `/usr/local/var/log/docker-mac-net-connect/std_error.log` it is empty.
Any suggestions here? Thanks.

**Comment by gregnr** [comment]
Hi @alexandertsukanov, happy to help and thanks for the details.

Just to confirm, did you run `brew services start ...` as root (`sudo`)?

**Comment by alexandertsukanov** [comment]
Hi, @gregnr!
Sorry for long response. I have changed my laptop. Looks like everything works fine 🙂 Thank you for quick reply.
