### ISSUE TITLE
I followed the instructions, but I failed. Can you help me

### ISSUE THREAD

**Issue by lafeier888** [chipmk/docker-mac-net-connect#7]
> I'm sure I started it

lafeier@lafeier-mac docker-projects % `brew services start chipmk/tap/docker-mac-net-connect`
```
/Users/lafeier/Library/LaunchAgents/homebrew.mxcl.docker-mac-net-connect.plist: service already loaded
Error: Failure while executing; `/bin/launchctl bootstrap gui/502 /Users/lafeier/Library/LaunchAgents/homebrew.mxcl.docker-mac-net-connect.plist` exited with 37.
```

> Get container IP

lafeier@lafeier-mac docker-projects % `docker inspect af01bf70c732|grep -i ipaddr`
```
            "SecondaryIPAddresses": null,
            "IPAddress": "",
                    "IPAddress": "192.168.80.6",
```
> execute the ping

lafeier@lafeier-mac docker-projects % `ping 192.168.80.6`
```
PING 192.168.80.6 (192.168.80.6): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
Request timeout for icmp_seq 3
```

**Comment by gregnr** [comment]
Hi @lafeier888 happy to help. Can you confirm that you ran the `brew` service as root (`sudo`)?
```
$ sudo brew services start chipmk/tap/docker-mac-net-connect
```

**Comment by lafeier888** [comment]
@gregnr Thank you. I found the reason. I need to restart docker for desktop
