### ISSUE TITLE
Is it possible to adopt this solution for Windows?

### ISSUE THREAD

**Issue by wrednamalpa** [chipmk/docker-mac-net-connect#9]
The situation with docker on Windows with WSL is very similar. Is it possible to adopt this solution for Windows platform?

**Comment by gregnr** [comment]
Hey @wrednamalpa, great question. Let me do some investigation on a Windows machine and get back to you.

**Comment by gregnr** [comment]
Hey @wrednamalpa sorry for the delay. The Docker website mentions the ability to connect to containers on Windows by IP:
https://docs.docker.com/desktop/networking/

Any chance you've tried this? I can't tell if they're talking about _any_ container on Windows (ie. Linux or Windows), or specifically Windows only (kernel) containers.

**Comment by gregnr** [comment]
Closing for now based on the above docs, but please reopen if this is not true on Windows.
